service: simple-dash-app-engine-app
runtime: python37

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 2

entrypoint: gunicorn -b 0.0.0.0:8080 main:server
